// Empire Ink — copy in NL + EN
// All visible page text routes through this, keyed by language

const EMPIRE_ASSETS = {
  logoFull: "https://empire-ink.nl/wp-content/uploads/2023/04/Logo-Empire-Ink-wit-scaled.webp",
  logoSmall: "https://empire-ink.nl/wp-content/uploads/2023/04/Logo-Empire-Ink-wit.webp",
  logoIcon: "https://empire-ink.nl/wp-content/uploads/2023/04/Logo-Empire-Ink-wit-300x300.png",
  heroBack: "https://empire-ink.nl/wp-content/uploads/2023/05/Rug-tattoo-cover.webp",
  bannerOverOns: "https://empire-ink.nl/wp-content/uploads/2023/05/banner-over-ons-1-1.webp",
  bannerContact: "https://empire-ink.nl/wp-content/uploads/2023/05/contact-header.webp",
  bannerPrijzen: "https://empire-ink.nl/wp-content/uploads/2023/08/PRIJZEN-ACTIES.webp",
  studioInterior: "https://empire-ink.nl/wp-content/uploads/2025/09/Empire-INK-071-scaled.webp",
  studioAction: "https://empire-ink.nl/wp-content/uploads/2025/09/Empire-INK-158-scaled.webp",
  piercerAction: "https://empire-ink.nl/wp-content/uploads/2023/09/Winish-Chedi-1-DSC_1949-1-scaled.webp",
  promoTrio: "https://empire-ink.nl/wp-content/uploads/2026/05/Empire-Ink-Monthly-Piercing-Deal-TRIO-SET-SPECIAL-Website-Actie-Visual.webp",
  promoDealOrNoDeal: "https://empire-ink.nl/wp-content/uploads/2026/05/Empire-Ink-Deal-or-No-Deal-Website-Actie-Visual-2.webp",
  comingSoon: "https://empire-ink.nl/wp-content/uploads/2025/09/Coming-Soon-scaled.webp",
};

const COPY = {
  nl: {
    locale: "nl-NL",
    topStrip: {
      open: "Open 7 dagen per week",
      addr: "Van Meekerenstraat 162 · Rotterdam",
      walkin: "Walk-ins welkom",
      rating: "9.6 op Google",
    },
    nav: {
      items: [
        { id: "tattoo", label: "Tattoo Info" },
        { id: "piercing", label: "Piercing Info" },
        { id: "portfolio", label: "Portfolio" },
        { id: "prijzen", label: "Prijzen & Acties" },
        { id: "over", label: "Over Ons" },
        { id: "contact", label: "Contact" },
      ],
      cta: "Boek Nu",
    },
    hero: {
      eyebrow: "Rotterdam · Sinds 2017",
      title1: "Jouw verhaal,",
      title2: "ons canvas",
      titleAccent: "verhaal",
      sub: "Acht artiesten. Drie piercers. Eén van de grootste studio's van Nederland. Premium werk, walk-ins welkom, zeven dagen per week.",
      primary: "Maak een Afspraak",
      secondary: "Bekijk Portfolio",
      scroll: "Scroll om te ontdekken",
    },
    proof: [
      { v: "9.6", l: "Google rating", icon: "star" },
      { v: "500m²", l: "Studio in Rotterdam-Zuid", icon: "square" },
      { v: "7 / 7", l: "Dagen per week open", icon: "clock" },
      { v: "GGD", l: "Gecertificeerde hygiëne", icon: "shield" },
    ],
    portfolio: {
      eyebrow: "Portfolio · 01",
      title: "Het werk",
      sub: "Een selectie uit duizenden uren. Filter op stijl om te ontdekken welke artiest bij jouw idee past.",
      tabs: ["Alles", "Realism", "Blackwork", "Dotwork", "Color", "Cover-ups"],
      view: "Bekijk volledig portfolio",
      pieces: [
        { artist: "Mees", style: "Realism", title: "Portret · Onderarm" },
        { artist: "Yara",  style: "Blackwork", title: "Rug · Composiet" },
        { artist: "Sem",   style: "Dotwork", title: "Mandala · Borst" },
        { artist: "Lina",  style: "Color", title: "Floral · Sleeve" },
        { artist: "Joris", style: "Cover-ups", title: "Cover · Bovenarm" },
        { artist: "Mees",  style: "Realism", title: "Tijger · Dij" },
        { artist: "Sem",   style: "Dotwork", title: "Geometrisch · Hand" },
        { artist: "Yara",  style: "Blackwork", title: "Slang · Schouder" },
      ],
    },
    artists: {
      eyebrow: "De crew · 02",
      title: "De artiesten",
      sub: "Acht handen, acht handschriften. Boek direct bij wie bij jouw idee past.",
      book: "Boek bij",
      roster: [
        { name: "Mees van Dijk",     styles: "Realism · Black & Grey", years: 12 },
        { name: "Yara Bakker",       styles: "Blackwork · Neo-Trad", years: 9 },
        { name: "Sem El-Hassan",     styles: "Dotwork · Mandala", years: 7 },
        { name: "Lina Visser",       styles: "Color · Illustrative", years: 6 },
        { name: "Joris ten Velde",   styles: "Cover-ups · Realism", years: 14 },
        { name: "Nika Petrov",       styles: "Fineline · Micro", years: 5 },
        { name: "Daan Mulder",       styles: "Japanese · Traditional", years: 11 },
        { name: "Iris Kwint",        styles: "Lettering · Script", years: 8 },
      ],
    },
    services: {
      eyebrow: "Diensten · 03",
      title: "Twee disciplines.",
      title2: "Eén standaard.",
      tattoo: {
        kicker: "Tattoo",
        body: "Van fineline tot full sleeve. Intake, ontwerp en ink-tijd inbegrepen vanaf het eerste consult.",
        from: "Vanaf",
        price: "€80",
        priceMeta: "incl. intake + ink-tijd",
        points: ["Persoonlijk ontwerp", "Vrijblijvend consult", "Garantie op afwerking"],
        cta: "Plan intake",
      },
      piercing: {
        kicker: "Piercing",
        body: "Drie ervaren piercers, dagelijks walk-in. Premium titanium en goud op voorraad, GGD-gecertificeerde hygiëne.",
        from: "Walk-in",
        price: "Dagelijks",
        priceMeta: "geen afspraak nodig",
        points: ["Premium titanium & 14K goud", "Direct terecht", "Nazorg inbegrepen"],
        cta: "Bekijk piercings",
      },
    },
    promo: {
      eyebrow: "Lopende actie · 04",
      title: "Trio Piercing Set",
      hook: "Drie premium piercings. Eén afspraak. Eén prijs.",
      price: "€99",
      priceWas: "€145",
      cta: "Claim deze deal",
      fine: "Aanbieding geldig t/m einde van de maand. Premium titanium inbegrepen. Op vertoon van legitimatie. Volg de huisregels voor minderjarigen.",
      badge: "Deze maand",
    },
    reviews: {
      eyebrow: "Reviews · 05",
      title: "Wat klanten zeggen",
      sub: "Gemiddeld 9.6 sterren over honderden reviews.",
      items: [
        { q: "De rust waarmee Mees werkte was ongelooflijk. Acht uur in de stoel voelde als twee. Het resultaat is exact wat ik voor ogen had — alleen beter.", name: "Sanne H.", piece: "Realism sleeve · 8u", rating: 5 },
        { q: "Walk-in piercing op zondag, binnen 20 minuten geholpen, alles steriel en uitgelegd. Dit is gewoon hoe het hoort.", name: "Daan K.", piece: "Helix · walk-in", rating: 5 },
        { q: "Ik kwam voor een cover-up van iets waar ik tien jaar last van had. Joris heeft er kunst van gemaakt. Geen woorden voor.", name: "Maria P.", piece: "Cover-up bovenarm", rating: 5 },
      ],
    },
    studio: {
      eyebrow: "De studio · 06",
      title: "Kom langs",
      sub: "500 vierkante meter. Acht kabines. Een aparte piercingsuite. Een wachtruimte waar je daadwerkelijk wilt wachten.",
      addrLabel: "Adres",
      hoursLabel: "Openingstijden",
      phoneLabel: "Bel ons",
      hoursLines: ["Ma — Vr · 11:00 — 21:00", "Za — Zo · 11:00 — 19:00"],
      directions: "Routebeschrijving",
    },
    cta: {
      title: "Klaar voor je",
      titleAccent: "volgende stuk",
      title2: "?",
      sub: "Plan een vrijblijvend consult of loop binnen. We zijn er — zeven dagen per week.",
      primary: "Boek Nu",
      secondary: "Bel 010 33 353 53",
    },
    footer: {
      tag: "Premium tattoo & piercing studio. Rotterdam, sinds 2017.",
      newsletter: "Nieuwsbrief",
      newsletterPh: "jouw@email.nl",
      newsletterCta: "Aanmelden",
      cols: [
        { title: "Studio", items: ["Tattoo Info", "Piercing Info", "Portfolio", "Artiesten"] },
        { title: "Bezoek", items: ["Over Ons", "Prijzen & Acties", "Contact", "Cadeaubonnen"] },
        { title: "Legal", items: ["Privacybeleid", "Algemene voorwaarden", "Huisregels", "Cookies"] },
      ],
      rights: "© 2026 Empire INK · KvK 12345678",
      credit: "Website door Monoliet.cloud",
    },
  },

  en: {
    locale: "en-GB",
    topStrip: {
      open: "Open 7 days a week",
      addr: "Van Meekerenstraat 162 · Rotterdam",
      walkin: "Walk-ins welcome",
      rating: "9.6 on Google",
    },
    nav: {
      items: [
        { id: "tattoo", label: "Tattoo Info" },
        { id: "piercing", label: "Piercing Info" },
        { id: "portfolio", label: "Portfolio" },
        { id: "prijzen", label: "Pricing & Deals" },
        { id: "over", label: "About" },
        { id: "contact", label: "Contact" },
      ],
      cta: "Book Now",
    },
    hero: {
      eyebrow: "Rotterdam · Since 2017",
      title1: "Your story,",
      title2: "our canvas",
      titleAccent: "story",
      sub: "Eight artists. Three piercers. One of the largest studios in the Netherlands. Premium work, walk-ins welcome, seven days a week.",
      primary: "Book a Session",
      secondary: "View Portfolio",
      scroll: "Scroll to explore",
    },
    proof: [
      { v: "9.6", l: "Google rating", icon: "star" },
      { v: "500m²", l: "Studio in Rotterdam-Zuid", icon: "square" },
      { v: "7 / 7", l: "Days open per week", icon: "clock" },
      { v: "GGD", l: "Certified hygiene", icon: "shield" },
    ],
    portfolio: {
      eyebrow: "Portfolio · 01",
      title: "The work",
      sub: "A selection from thousands of hours. Filter by style to find the artist that matches your idea.",
      tabs: ["All", "Realism", "Blackwork", "Dotwork", "Color", "Cover-ups"],
      view: "View full portfolio",
      pieces: [
        { artist: "Mees", style: "Realism", title: "Portrait · Forearm" },
        { artist: "Yara",  style: "Blackwork", title: "Back · Composite" },
        { artist: "Sem",   style: "Dotwork", title: "Mandala · Chest" },
        { artist: "Lina",  style: "Color", title: "Floral · Sleeve" },
        { artist: "Joris", style: "Cover-ups", title: "Cover · Upper arm" },
        { artist: "Mees",  style: "Realism", title: "Tiger · Thigh" },
        { artist: "Sem",   style: "Dotwork", title: "Geometric · Hand" },
        { artist: "Yara",  style: "Blackwork", title: "Snake · Shoulder" },
      ],
    },
    artists: {
      eyebrow: "The crew · 02",
      title: "The artists",
      sub: "Eight hands, eight signatures. Book directly with the one that fits your idea.",
      book: "Book with",
      roster: [
        { name: "Mees van Dijk",     styles: "Realism · Black & Grey", years: 12 },
        { name: "Yara Bakker",       styles: "Blackwork · Neo-Trad", years: 9 },
        { name: "Sem El-Hassan",     styles: "Dotwork · Mandala", years: 7 },
        { name: "Lina Visser",       styles: "Color · Illustrative", years: 6 },
        { name: "Joris ten Velde",   styles: "Cover-ups · Realism", years: 14 },
        { name: "Nika Petrov",       styles: "Fineline · Micro", years: 5 },
        { name: "Daan Mulder",       styles: "Japanese · Traditional", years: 11 },
        { name: "Iris Kwint",        styles: "Lettering · Script", years: 8 },
      ],
    },
    services: {
      eyebrow: "Services · 03",
      title: "Two disciplines.",
      title2: "One standard.",
      tattoo: {
        kicker: "Tattoo",
        body: "From fineline to full sleeve. Consult, design and ink time included from the first session.",
        from: "From",
        price: "€80",
        priceMeta: "incl. consult + ink time",
        points: ["Custom design", "Free consultation", "Aftercare guarantee"],
        cta: "Book a consult",
      },
      piercing: {
        kicker: "Piercing",
        body: "Three experienced piercers, walk-in every day. Premium titanium and gold in stock, GGD-certified hygiene.",
        from: "Walk-in",
        price: "Daily",
        priceMeta: "no appointment needed",
        points: ["Premium titanium & 14K gold", "Same-day service", "Aftercare included"],
        cta: "See piercings",
      },
    },
    promo: {
      eyebrow: "Current deal · 04",
      title: "Trio Piercing Set",
      hook: "Three premium piercings. One sitting. One price.",
      price: "€99",
      priceWas: "€145",
      cta: "Claim this deal",
      fine: "Offer valid until end of month. Premium titanium included. Valid ID required. House rules apply to minors.",
      badge: "This month",
    },
    reviews: {
      eyebrow: "Reviews · 05",
      title: "What clients say",
      sub: "Averaging 9.6 stars across hundreds of reviews.",
      items: [
        { q: "The calm Mees worked with was unreal. Eight hours in the chair felt like two. The result is exactly what I had in mind — only better.", name: "Sanne H.", piece: "Realism sleeve · 8h", rating: 5 },
        { q: "Walk-in piercing on a Sunday, helped within 20 minutes, everything sterile and explained. This is just how it should be.", name: "Daan K.", piece: "Helix · walk-in", rating: 5 },
        { q: "I came in for a cover-up of something I'd hated for ten years. Joris turned it into art. No words.", name: "Maria P.", piece: "Cover-up upper arm", rating: 5 },
      ],
    },
    studio: {
      eyebrow: "The studio · 06",
      title: "Come by",
      sub: "500 square metres. Eight booths. A separate piercing suite. A waiting area you actually want to wait in.",
      addrLabel: "Address",
      hoursLabel: "Opening hours",
      phoneLabel: "Call us",
      hoursLines: ["Mon — Fri · 11:00 — 21:00", "Sat — Sun · 11:00 — 19:00"],
      directions: "Get directions",
    },
    cta: {
      title: "Ready for your",
      titleAccent: "next piece",
      title2: "?",
      sub: "Schedule a free consultation or walk in. We're here — seven days a week.",
      primary: "Book Now",
      secondary: "Call 010 33 353 53",
    },
    footer: {
      tag: "Premium tattoo & piercing studio. Rotterdam, since 2017.",
      newsletter: "Newsletter",
      newsletterPh: "you@email.com",
      newsletterCta: "Subscribe",
      cols: [
        { title: "Studio", items: ["Tattoo Info", "Piercing Info", "Portfolio", "Artists"] },
        { title: "Visit", items: ["About", "Pricing & Deals", "Contact", "Gift cards"] },
        { title: "Legal", items: ["Privacy policy", "Terms", "House rules", "Cookies"] },
      ],
      rights: "© 2026 Empire INK · KvK 12345678",
      credit: "Website by Monoliet.cloud",
    },
  },
};

Object.assign(window, { COPY, EMPIRE_ASSETS });
